### ISSUE TITLE
2 fichiers en doublon ?

### ISSUE THREAD

**Issue by romthi38** [PnEcrins/FollowDem#17]
Il y a un fichier ``api.class.php`` dans le dossier ``/classes``, ce fichier contient de nombreuses portions de code commentées, pourquoi ?
Il y a un fichier ``api.class.php`` dans le dossier ``/config``, des portions de code sont similaire au fichier ci-desses.
Serait-ce un doublon ?

**Comment by nienfba** [comment]
Le fichier /config/api.class.php ne sert à rien ! Il peut-être supprimé.

**Comment by romthi38** [comment]
C'est supprimé, merci !

2015-06-18 16:31 GMT+02:00 Fabien <notifications@github.com>:
