### ISSUE TITLE
Import de données

### ISSUE THREAD

**Issue by romthi38** [PnEcrins/FollowDem#18]
L'import de données par un fichier txt possédant la même structure que dans la config ne marche pas.
Idem pour l'import de données en ajoutant des lignes dans le fichier ``tracked_objects.csv``.

**Comment by camillemonchicourt** [comment]
Tu veux dire quand tu lance la tache ``url/controler/import_imap_csv``?

Peut-être car cette tache cherche d'abord à se connecter à une boite email pour en extraire les TXT en PJ... ?

Il faudrait ajouter des paramètre pour permettre différents types d'imports des données.

**Comment by nienfba** [comment]
url/controler/import_imap_csv 
=> se connecte à une boîte IMAP, récupère les pièces jointes et créé un unique fichier csv.
=> L'import du CSV dépend du tableau associatif $config['csv_colonne'] (nom_donnee => index csv) 

mais il est aussi possible d'appeler 
url/controler/import_csv
=> recherche le fichier : (csv/tracked_objects.csv) config::get('rep_appli').'csv'.config::get('system_separateur').'tracked_objects.csv'
=> import selon la définition du tableau associatif  $config['csv_colonne'] (nom_donnee => index csv)

**Comment by camillemonchicourt** [comment]
OK super ! 
Je ne connaissais cette autre tache.
Je l'ai donc mentionnée dans la doc : https://github.com/PnEcrins/FollowDem/commit/5f5f425a8953ce40c14f6bff8b68d0f534f0581e

Merci.

**Comment by romthi38** [comment]
Après avoir appelé ``url/controler/import_csv``, j'ai l'erreur suivante qui apparaît :

    Fatal error: Call to a member function save() on a non-object in   /var/www/followdem/classes/tracked_objects.class.php on line 200

**Comment by romthi38** [comment]
J'ai corrigé l'erreur du fichier ``/classes/tracked_objects.class.php``.

Malheureusement, apparition d'une nouvelle erreur.

    Message :Impossible de charger /var/www/followdem/classes/data/data.class.php.
Code :0
Fichier :/var/www/followdem/config/bootstrap.php
ligne :72
Trace :#0 /var/www/followdem/classes/tracked_objects.class.php(441): __autoload('data')
#1 /var/www/followdem/classes/controler/controler.class.php(191): tracked_objects::import_csv()
#2 /var/www/followdem/classes/controler/controler.class.php(37): controler->import_csv()
#3 /var/www/followdem/index.php(20): controler->__construct('import_csv')
#4 {main}

**Comment by romthi38** [comment]
Bon, j'ai trouvé l'erreur, c'était le nom d'une variable.
Maintenant l'import du csv marche.

Par contre, les données ne sont pas mises à jour sur l'application.

**Comment by nienfba** [comment]
Cela me semble étonnant ces erreurs. Normalement import_csv fonctionne bien puisqu'il est utilisé par l'import classique IMAP en cours de production. Le problème doit donc venir d'ailleurs ou est plus global. Tu as documentés tes modifications ? Elles sont à quel endroit master/dev/ local ? Quel fichiers CSV utilises tu pour tester l'import ?

**Comment by romthi38** [comment]
En fait, lorsque j'ai commencé à dépersonnaliser l'application, j'ai
modifié le nom des variables.

Je pensais que tout marchait, mais en fait j'avais oublié de modifier 2-3
noms de variables, ce qui a provoqué ce bug.
La variable que je n'avais pas modifié se trouvait dans le fichier
/config/api.class.php

Les modifs sont en local, depuis 3 jours je n'arrive plus à push tout ce
que je fais en local sur la branche Develop, j'attends Gil pour qu'il
m'aide.

J'ai utilisé le fichier tracked_objects.csv pour tester l'import (j'ai
ajouté les données à la main).

Merci pour l'aide ;)
