### ISSUE TITLE
Fichier config/carto.php à éditer ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/FollowDem#25]
Si je comprends bien, ce fichier sert à définir des fonds carto ?
Or on les gère dans le fichier ``/config/config.php``.
Si ce fichier est utile en temps que bibliothèque de fonds utilisables (?), peut-on se dédouaner de devoir le modifier (juste la clé IGN) pour que les gens ne modifient que ``config/carto.php`` ?

**Comment by nienfba** [comment]
il semble que ce fichier soit obsolète (inutilisé)
La génération de la carte Leaflet est effectué dans le fichier api.class.php et on retrouve ligne 65 :+1: 

        	foreach(config::get('leaflet_fonds_carte') as $nom=>$param)
		{
			$leaflet_ini .= 'var '.$nom.' = new L.TileLayer(\''.$param['url'].'\', {maxZoom: '.$param['maxZoom'].', attribution: \''.$param['attribution'].'\', subdomains: '.json_encode($param['subdomains']).'});';
			$tmp_control_map[$param['name']] = $nom;
		}

Donc les fonds de cartes sont bien issus du paramètre de configuration 

             config::get('leaflet_fonds_carte')

**Comment by camillemonchicourt** [comment]
@romthi38 confirme après test. 
Parfait, du coup on va virer ce fichier et j'ai mis à jour la doc : https://github.com/PnEcrins/FollowDem/commits/develop
