### ISSUE TITLE
[admin] Améliorer pagination

### ISSUE THREAD

**Issue by romthi38** [PnEcrins/FollowDem#42]
Permettre de naviguer pas seulement grâce aux boutons "précédent" et "suivant" mais aussi grâce à des numéros.

**Comment by JeanLenormand** [comment]
Plutôt utiliser la pagination de BOOTSTRAP pour voir le nombre de page, passer plus facilement de page en page, voir le nombre total d'objets etc... https://getbootstrap.com/docs/4.0/components/pagination/

**Comment by camillemonchicourt** [comment]
Admin entièrement re-développée dans un dépôt dédié : https://github.com/PnEcrins/FollowDem-admin-front/tree/ns-flw
