### ISSUE TITLE
Améliorer la gestion des différents fonds carto

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/FollowDem#6]
- Permettre de choisir entre IGN Geoportail, OpenStreetMap, Google Maps ou de les combiner
- Gérer les fonds à afficher dans la CONF
- Documenter cette CONF

**Comment by nienfba** [comment]
Lds fonds de carte dsont déjà défini dans le fichier config ligne 282

       /* Leaflet paramètres des fonds de cartes et des pictos 
       Pour tout autre paramètres, utiliser bottom.js dans js/ */

	/**
	*	leaflet_fonds_carte
	*	Paramètres des fonds de carte - Google géré à part. Voir gmap plus bas
	*	Penser à remplacer la valeur de maCleIgn dans 'url'.
	*	
	*	@var	array
	*/

	$config['leaflet_fonds_carte'] = array(
		"IGNCARTE"=>array(
			'name'=>'Carte IGN',
			'url'=>'http://gpp3-wxs.ign.fr/maCleIgn/geoportail/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
			'attribution'=>'IGN',
			'maxZoom'=>17,
			'subdomains'=>''
		),
		"IGNPHOTO"=>array(
			'name'=>'Photo aérienne IGN',
			'url'=>'http://gpp3-wxs.ign.fr/maCleIgn/geoportail/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
			'attribution'=>'IGN',
			'maxZoom'=>19,
			'subdomains'=>''
		),
		"IGNCARTEDET"=>array(
			'name'=>'Carte détaillée IGN',
			'url'=>'http://gpp3-wxs.ign.fr/maCleIgn/geoportail/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
			'attribution'=>'IGN',
			'maxZoom'=>17,
			'subdomains'=>''
		),
		"OSM"=>array(
			'name'=>'OpenStreetMap',
			'url'=>'http://{s}.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.png',
			'attribution'=>'Tiles courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a>. Map data (c) <a href="http://www.openstreetmap.org/" target="_blank">OpenStreetMap</a> contributors, CC-BY-SA.',
			'maxZoom'=>19,
			'subdomains'=>array("otile1", "otile2", "otile3", "otile4")
		)
	);
	
	/**
	*	leaflet_fonds_carte_defaut
	*	Fond de carte par dafaut - GoogleLayer pour googleMap
	*
	*	@var	array
	*/
	
	// $config['leaflet_fonds_carte_defaut'] = "IGNCARTE";
	$config['leaflet_fonds_carte_defaut'] = "OSM";

il y a aussi la possibilité d'attacher les fonds de cartes google avec le paramètres ligne 387 :

	/**
	*	leaflet_gmap 
	*	Chargement des fond de carte GoogleMAP
	*	Chargement de l'API google et du plugin LeafLet Gmap
	*
	*	@var	boolean
	*/	
	$config['leaflet_gmap'] = false;

**Comment by nienfba** [comment]
* Permettre de choisir entre IGN Geoportail, OpenStreetMap, Google Maps ou de les combiner : rajouter les données dans le tableau de conf : $config['leaflet_fonds_carte']

* Gérer les fonds à afficher dans la CONF : modifier simplement la liste dans le tableau de conf : $config['leaflet_fonds_carte']

* Documenter cette CONF : to do ;)

**Comment by camillemonchicourt** [comment]
Yes !
